openshift/service-ca-operator

- .travis.yml
1.10 didn't seem to work. This matches the original repo .travis.yml
> set .travis.yml golang to 1.9

- pkg/operator/sync_signer_v4_00.go
Prolong the life of the service signing CA from 10 days to 730.
> Make the signing CA last 1 year

- manifests/0000_09_service-ca-operator_02_crd.yaml
@mrogers950  I used [this generator](https://github.com/openshift/kubernetes-sigs-controller-tools/cmd/crd) to generate the CRD.
A few tweaks after generation:
- add `singular: serviceca` bc this comment doesn't exist in openshift/api/operator/v1/types_serviceca.go: `// +serviceca:singular=serviceca`
- removed generated status fields, don't need to validate those 
-  removed `required` for most fields
this PR is similar to [this](https://github.com/openshift/cluster-authentication-operator/pull/80)
> OpenAPIV3 validation for operator CRD

- pkg/controller/api/api.go
- pkg/controller/apiservicecabundle/controller/apiservice_cabundle_controller_test.go
- pkg/controller/configmapcainjector/controller/configmap_injecting_controller_test.go
- pkg/controller/servingcert/controller/secret_creating_controller.go
- pkg/controller/servingcert/controller/secret_creating_controller_test.go
- pkg/controller/servingcert/controller/secret_updating_controller.go
- pkg/controller/servingcert/controller/secret_updating_controller_test.go
- test/e2e/e2e_test.go
This PR makes it so that `service.beta.openshift.io` variants of the annotations are honored, and both alpha and beta variants of the accounting annotations (errors, expiry, etc) are added to objects to make it easier to transition to beta completely. 
/cc @openshift/sig-auth
> Honor beta SSCS annotations

- bindata/v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/signing-cabundle.yaml
- bindata/v4.0.0/configmap-cabundle-controller/defaultconfig.yaml
- bindata/v4.0.0/configmap-cabundle-controller/signing-cabundle.yaml
- pkg/operator/sync_apiservice_v4_00.go
- pkg/operator/sync_configmapcabundle_v4_00.go
- pkg/operator/v4_00_assets/bindata.go
Be consistent with other components and use the key 'ca-bundle.crt'
instead of 'cabundle.crt' for CA bundle data in configmaps.
> refactor(bindata,sync): update configmap key to 'ca-bundle.crt'

- manifests/0000_09_service-ca-operator_05_deploy.yaml
- manifests/image-references
This is what ART is looking for:
```console
$ oc adm release new --from-image-stream=4.0-art-latest -n ocp --to-dir=/tmp/release --reference-mode=source
info: Found 141 images in image stream
...
Loading manifests from service-ca-operator: sha256:4fa49d7b421f5bb5fed9d99de71338fbbd0be5613645bff1353069da1400443d ...
info: Included 73 referenced images into the payload
error: unable to create a release: operator "service-ca-operator" failed to map images: image file "/tmp/release-image-0.0.1-2019-03-12-222249977939869/service-ca-operator/image-references" referenced image "service-ca" that is not part of the input images
```
and while we don't know how to fix ART to look for the service-ca name, we do know how to adjust the name here ;).
> manifests: Rename origin-service-ca -> origin-service-ca-operator

- bindata/v4.0.0/apiservice-cabundle-controller/defaultconfig.yaml
- bindata/v4.0.0/configmap-cabundle-controller/defaultconfig.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/defaultconfig.yaml
- pkg/boilerplate/controller/filter.go
- pkg/controller/configmapcainjector/controller/configmap_injecting_controller.go
- pkg/controller/servingcert/controller/secret_creating_controller.go
- pkg/controller/servingcert/controller/secret_creating_controller_test.go
- pkg/operator/sync.go
- pkg/operator/sync_common.go
- pkg/operator/v4_00_assets/bindata.go
- test/e2e/e2e_test.go
This PR contains a few changes that lets all secrets and configmaps (and API service bundles) be updated when you run `oc delete secret/service-serving-cert-signer-signing-key -n openshift-service-ca `
- Always trigger new deployments of the 3 controllers whenever a controller resource is changed. 
- Fix replacement of the CA bundle when the signing key changes. 
- Allow regeneration of a cert in an existing secret, and refactor the secret update error reporting.
@openshift/sig-auth
> Allow deletion of signing key secret for CA regeneration

- pkg/operator/operator.go
- pkg/operator/operatorclient/operatorclient.go
- pkg/operator/starter.go
- pkg/operator/status.go
Switch to using library-go/operator v1helpers.UpdateStatus and other improvements in status reporting
Summary of status reporting (3 deployments == configmap-cabundle-injector, apiservice-cabundle-injector, and serving-cert-signer) :
```
Available=True | VersionUpdate=True | Progressing=False
* All replicas of each of the 3 deployments is running
* No instances running from previous deployments
Available=True | VersionUpdate=True | Progressing=True
* At least 1 replica of each of the 3 deployments is running
* No instances running from previous deployments
* Not all replicas of each of the 3 deployments exist, still deploying
Available=True | VersionUpdate=False | Progressing=True
* At least 1 replica of each of the 3 deployments is running
* Instances found running from previous …
```
> Improve/fix version,status reporting for service-ca clusteroperator

- pkg/controller/servingcert/controller/secret_creating_controller.go
- pkg/controller/servingcert/controller/secret_creating_controller_test.go
Since we don't own the annotated service, the signed-by annotation might be overwritten by the owner, leading to continuous cert regeneration. Perform the issuer check by parsing the cert instead of relying on the signed-by annotation.
https://bugzilla.redhat.com/show_bug.cgi?id=1700037
> Bug 1700037: Check cert issuer directly

- pkg/boilerplate/operator/option.go
Cause: operator used an emoji as the operator informer key
Consequence: error logs contain emoji character, confusing users
Fix: change key to more boring but informative value
Result: errors from operator controller shows "service-ca-operator"
instead of emoji
> Bug 1664421: remove emoji from event logs

- manifests/0000_09_service-ca-operator_03_operator.cr.yaml
- pkg/operator/starter.go
- pkg/operator/v4_00_assets/bindata.go
Use the CVO to manage the operator config, instead of deprecated config helper
> Use CVO for operator config

- bindata/v4.0.0/apiservice-cabundle-controller/ns.yaml
- bindata/v4.0.0/configmap-cabundle-controller/ns.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/ns.yaml
- manifests/0000_09_service-ca-operator_01_namespace.yaml
- pkg/operator/v4_00_assets/bindata.go
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
> Add node-selector annotation to namespace

- bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/signing-secret.yaml
- pkg/controller/api/resourcenames.go
- pkg/operator/v4_00_assets/bindata.go
- test/e2e/e2e_test.go
@openshift/sig-auth 
Shortening this name will be useful because we have one step in the documentation that will reference the secret (force rotate service CA), making it effectively an API.
> Shorten signing key secret name

- manifests/03_cm.yaml
Enable Auth for metrics endpoint in [service-ca-operator](https://github.com/openshift/service-ca-operator).
By default delegated authentication and authorization are enabled.
Currently the configmap explicitly disables delegated authentication and authorization.
Remove the override to enable delegated authentication and authorization.
See https://github.com/openshift/cluster-authentication-operator/pull/123 which solves the same problem for [openshift/cluster-authentication-operator](https://github.com/openshift/cluster-authentication-operator).
> Enable Auth for metrics endpoint

- bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
- bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
- manifests/05_deploy.yaml
- pkg/operator/v4_00_assets/bindata.go
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
> Fix tolerations

- bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
- bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
- manifests/05_deploy.yaml
- pkg/operator/v4_00_assets/bindata.go
Prevent pods from eviction, OOMKilling, and CPU starvation when
running in the BestEffort QoS by setting resource requests.
https://github.com/openshift/origin/pull/22787
Limits used:
Memory:
service-ca-operator 80Mi
apiservice-cabundle-injector 50Mi
configmap-cabundle-injector 50Mi
service-serving-cert-signer 120Mi
CPU:
all 10m
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1711075
> bug 1711075: set resource requests on containers

- pkg/operator/operator.go
In case the Degraded condition is not set to False, the union will set it as Degraded=Unknown with NoData as reason (because we haven't said whether we are or not degraded).
This will always set degraded to false when there is no error returned from the loop.
> status: do not flap degraded from false to unknown

- pkg/controller/api/api.go
- pkg/controller/servingcert/controller/secret_creating_controller.go
The addition of CA rotation also saw the removal of the signing CA from generated serving certificates. This broke legacy clients that depended on this behavior. To support code-free changes to those legacy clients, this change maintains the old behavior of including the signing CA so long as the alpha annotation is used. Beta and above will not include the signing CA.
> Revert the removal of the service CA from serving certs

- pkg/operator/config.go
- pkg/operator/rotate.go
- pkg/operator/rotate_test.go
- test/e2e/e2e_test.go
It can still be enabled via an unsupported config override to allow the codepath to remain tested in e2e. It is intended to be enabled in a future release.
> Disable automatic CA rotation for now

- pkg/operator/cert.go
- pkg/operator/config.go
- pkg/operator/rotate.go
- pkg/operator/rotate_test.go
- pkg/operator/sync_common.go
- pkg/operator/sync_common_test.go
- test/e2e/e2e_test.go
- test/util/cert.go
Setting the duration of CA validity allows setting a short duration to test operator compatibility with CA rotation.
This PR is required by the proposed periodic rotation compatibility job:  https://github.com/openshift/release/pull/5930
> Support setting CA validity duration via unsupportedConfigOverrides

- README.md
- bindata/v4.0.0/controller/clusterrole.yaml
- pkg/controller/cabundleinjector/mutatingwebhook.go
- pkg/controller/cabundleinjector/starter.go
- pkg/controller/cabundleinjector/validatingwebhook.go
- pkg/operator/v4_00_assets/bindata.go
- test/e2e/e2e_test.go
This PR adds support for injection of service CA bundle for `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration`, and supersedes #51.
Fixes #63 
Co-authored-by: Daniel Spangenberg <daniel.spangenberg@redhat.com>
> Enable injection of service CA bundle for admission webhooks 

- pkg/operator/rotate.go
Ensuring the CA duration exceeds the maximum supported upgrade interval (12 months) reduces the risk of services ending up using outdated key material.
The need for this change was documented in more detail in the related enhancement PR: https://github.com/openshift/enhancements/pull/181
> Extend service CA duration to 14 months

- pkg/controller/api/api.go
- pkg/controller/cabundleinjector/apiservice.go
- pkg/controller/cabundleinjector/configmap.go
- pkg/controller/cabundleinjector/crd.go
- pkg/controller/cabundleinjector/mutatingwebhook.go
- pkg/controller/cabundleinjector/starter.go
- pkg/controller/cabundleinjector/validatingwebhook.go
Only the beta ca bundle injection annotation (`service.beta.openshift.io/inject-cabundle`) should be supported for types added in 4.4. Existing types will continue to support both the alpha and beta annotations.
> Update new bundle injection targets to only support beta annotation

- pkg/controller/cabundleinjector/starter.go
#102 changed the check for annotation for injection to be case-sensitive, which represented a regression.
> Fix CA bundle annotation check to be case-insensitive

- test/e2e/e2e_test.go
Adds an e2e test to check service serving certificate is recreated if the secret is deleted and it matches the certificate received by the client pod
> e2e test to check service serving cert using client pod

- pkg/operator/config.go
- pkg/operator/rotate.go
- pkg/operator/rotate_test.go
- test/e2e/e2e_test.go
This option was only added to disable the feature in 4.3 and is not necessary for a release that enables automated rotation.
I was tempted to just remove all unsupported configuration options since it's generally more useful to test each service for rotation compatibility in isolation, but that could be a more controversial discussion.
/cc @stlaz @sttts
> Remove the option to disable automated CA rotation

- pkg/operator/rotate.go
As per https://github.com/openshift/enhancements/pull/193
> Update CA duration to 26 months to ensure upgrade after rotation

- pkg/operator/metrics/metrics.go
- pkg/operator/sync_common.go
- test/e2e/e2e_test.go
This PR is an attempt to add expiry time and time left metrics before the signer CA expires to Prometheus collector
> Bug 1803282: enable signer ca expiry timer metrics

- pkg/operator/starter.go
This PR is in support of a 4.4 PR that unifies all service ca controllers into a single deployment to simplify maintenance and administration: https://github.com/openshift/service-ca-operator/pull/89
> Bug 1791022: Ensure removal of 4.4-only resources on downgrade to 4.3

- manifests/05_deploy.yaml
Rename the operator container to allow for more reasonable debugging.
> Bug 1876858: manifests: rename operator container to be more descriptive

- manifests/0000_90_service-ca-operator_01_prometheusrole.yaml
- manifests/0000_90_service-ca-operator_02_prometheusrolebinding.yaml
- manifests/0000_90_service-ca-operator_03_servicemonitor.yaml
- manifests/00_roles.yaml
- manifests/01_namespace.yaml
- manifests/02_service.yaml
- manifests/03_cm.yaml
- manifests/03_operator.cr.yaml
- manifests/04_sa.yaml
- manifests/05_deploy.yaml
- manifests/07_clusteroperator.yaml
This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all service-ca-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.
> Annotate manifests for single-node-developer cluster profile

- test/util/rotate.go
failing with
```
go vet -mod=vendor ./...
test/util/rotate.go:113:4: call to (*T).Fatalf from a non-test goroutine
```
Aborting the test from inside a goroutine is invalid; instead, just mark the test as failed, and let the client on the main goroutine time out. By default, that waits too long and the test fails with a generic "timed out" panic, and no record of the cause, so impose a 1-minute connection/client timeout to ensure the test fails in time; 1 minute should be plenty.
We could do more work to fail immediately (e.g. by moving the client into a separate goroutine and having the main test goroutine wait for either of the client and server), but this seems good enough for an error we don't expect to happen.
> Fix (make verify) with Go 1.16

- pkg/controller/servingcert/controller/secret_updating_controller.go
- pkg/controller/servingcert/controller/secret_updating_controller_test.go
This should not change behavior, because the only non-test caller is passing in the same value.
Then fix tests that looked like they were using 1-hour time window, but actually depended on a default-initialized zero value.
> Don't ignore the minTimeLeft parameter to requiresRegeneration

- pkg/controller/servingcert/controller/secret_creating_controller.go
- pkg/controller/servingcert/controller/secret_creating_controller_test.go
- pkg/operator/operator.go
- pkg/operator/rotate_test.go
- pkg/operator/sync.go
- pkg/operator/sync_common.go
… noticed while working on other things, or just to silence Visual Studio Code warnings.
See individual commit messages for details.
> Random cleanups

- test/e2e/e2e_test.go
- test/util/rotate.go
This is a set of fixes to e2e tests
- fixing some bugs (or short timeouts) that show up as flakes (e.g. in https://prow.ci.openshift.org/pr-history/?org=openshift&repo=service-ca-operator&pr=143 )
- improving the code to make test development easier
- a few minor cleanups.
See individual commit messages for details.
Note primarily the commit “Don't abort metrics/service-ca-metrics before the sync finishes”, where I could see an argument that this should be changed in the code instead of the tests.
> Various e2e test fixes and cleanups

- Makefile
- go.mod
- go.sum
- manifests/05_deploy-ibm-cloud-managed.yaml
- manifests/05_deploy.yaml
- profile-patches/ibm-cloud-managed/05_deploy.yaml-patch
- vendor/github.com/openshift/build-machinery-go/OWNERS
- vendor/github.com/openshift/build-machinery-go/README.md
- vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
- vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
- vendor/modules.txt
Bumps build-machinery-go to latest
Adds patch specific to ibm-cloud-managed profile that removes node selector for operator deployment
make verify verifies that the generated manifest is up to date
make update updates the manifest by applying the ibm-cloud-managed patch to the original deployment manifest
This is needed for the IBM Cloud managed profile because in that profile there are no master nodes.
> IBM Cloud manifest profile patch

- bindata/v4.0.0/controller/deployment.yaml
- bindata/v4.0.0/controller/ns.yaml
- manifests/01_namespace.yaml
- manifests/05_deploy-ibm-cloud-managed.yaml
- manifests/05_deploy.yaml
- pkg/operator/v4_00_assets/bindata.go
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
> Add management workload annotations

- bindata/v4.0.0/controller/deployment.yaml
- manifests/05_deploy-ibm-cloud-managed.yaml
- manifests/05_deploy.yaml
- pkg/operator/v4_00_assets/bindata.go
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
> Rename workload annotations

- pkg/operator/operator.go
- pkg/operator/status.go
... and this will also, via library-go/pkg/operator/status, show up in ClusterOperators/service-ca , which was previously reporting the default upgradeable Statu: Unknown, Reason: NoData.
https://bugzilla.redhat.com/show_bug.cgi?id=1948012
> Bug 1948012: Report the operator status as always upgradeable in serviceCA/cluster

- pkg/controller/api/api.go
- pkg/controller/cabundleinjector/configmap.go
- pkg/controller/cabundleinjector/starter.go
- test/e2e/e2e_test.go
…the old service-ca.crt content in SA tokens
This is a manual pick of #167 
Fixes the e2e_test and obsoletes https://github.com/openshift/service-ca-operator/pull/169
> [release-4.7] bug 1981634: add vulnerable legacy injector to allow for upgrade clusters to use

- manifests/0000_90_service-ca-operator_03_servicemonitor.yaml
The CMO is now capable of using client cert auth to scrape the metrics endpoints. Use that in our components to reduce API load and allow metrics collection when the API is down - given further authz conditions are met.
/assign @s-urbaniak
>  Bug 1986829: metrics: use client cert auth for metrics scraping

- pkg/operator/operator.go
- pkg/operator/starter.go
- pkg/operator/sync.go
- pkg/operator/sync_common.go
- pkg/operator/sync_common_test.go
- pkg/operator/sync_test.go
If running on an external control plane topology, there are no master
nodes. Adds a check and removes the service-ca deployment's master node
selector when running on a cluster with external control plane.
> Bug 1987029: Support external control plane topology

- OWNERS
This is consumed by [ART's doozer][1], and also makes it easier for folks who know which repository is bugged to file their bugs appropriately.
[1]: https://github.com/openshift/doozer/blob/aa5c59b15496fbb69ca140b2cf5506dca4daee20/doozerlib/metadata.py#L288-L343
> OWNERS: Add Bugzilla component

- manifests/05_deploy-ibm-cloud-managed.yaml
- manifests/05_deploy.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-service-ca-operator/deployments/service-ca-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"service-ca-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabi
lities (container \"service-ca-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), seccompProfile (pod or container \"service-ca-operator\" must set securityContext.seccompProfile.type to …
```
> manifests/deployment: comply to restricted pod security level

- manifests/0000_10_openshift_service-ca_00_namespace.yaml
When installing SNO openshift-service-ca service-ca pod takes a few minutes to start. Creating the serivce-ca namespace early allows it to get openshift.io/sa.scc.uid-range annotation and start running earlier.
> API-1525: Add openshift_service-ca namespace yaml to manifests dir

- bindata/v4.0.0/controller/signing-cabundle.yaml
- bindata/v4.0.0/controller/signing-secret.yaml
- pkg/controller/api/api.go
- pkg/controller/cabundleinjector/configmap.go
- pkg/controller/servingcert/controller/secret_creating_controller.go
- pkg/controller/servingcert/controller/secret_creating_controller_test.go
- pkg/controller/servingcert/controller/secret_updating_controller.go
- pkg/operator/v4_00_assets/bindata.go
- vendor/github.com/openshift/api/annotations/annotations.go
- vendor/modules.txt
The openshift/api field will merge and be revendored here.
serving secrets and injected configmaps are not shared, we stomp all the keys.  Add the service-ca as the owner of these configmaps since we control the content.
> add ownership for unshared secrets and configmaps

- bindata/v4.0.0/controller/deployment.yaml
- manifests/05_deploy-ibm-cloud-managed.yaml
- manifests/05_deploy.yaml
- pkg/operator/v4_00_assets/bindata.go
All openshift operators must include FallbackToLogsOnError to ease debugging.
> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
Updating ose-service-ca-operator-container image to be consistent with ART for 4.20
> OCPBUGS-57703: Updating ose-service-ca-operator-container image to be consistent with ART for 4.20
