openshift/service-ca-operator

- pkg/controller/configmapcainjector/configmap_injecting_controller_test.go
> fix configmap injector test

- pkg/operator/operatorclient/operatorclient.go
- pkg/operator/starter.go
for after https://github.com/openshift/service-ca-operator/pull/19
> Sync service ca

- bindata/v4.0.0/apiservice-cabundle-controller/clusterrolebinding.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/cm.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/ns.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/role.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/rolebinding.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/sa.yaml
- bindata/v4.0.0/apiservice-cabundle-controller/signing-cabundle.yaml
- bindata/v4.0.0/configmap-cabundle-controller/clusterrolebinding.yaml
- bindata/v4.0.0/configmap-cabundle-controller/cm.yaml
- bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
- bindata/v4.0.0/configmap-cabundle-controller/ns.yaml
- bindata/v4.0.0/configmap-cabundle-controller/role.yaml
- bindata/v4.0.0/configmap-cabundle-controller/rolebinding.yaml
- bindata/v4.0.0/configmap-cabundle-controller/sa.yaml
- bindata/v4.0.0/configmap-cabundle-controller/signing-cabundle.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/clusterrolebinding.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/cm.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/ns.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/role.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/rolebinding.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/sa.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/signing-secret.yaml
- pkg/cmd/apiservicecabundle/cmd.go
- pkg/cmd/configmapcabundle/cmd.go
- pkg/cmd/servingcertsigner/cmd.go
- pkg/operator/operatorclient/interfaces.go
- pkg/operator/v4_00_assets/bindata.go
- test/e2e/e2e_test.go
> replace openshift-service-cert-signer with openshift-service-ca

- test/e2e/e2e_test.go
> e2e: Fix operator pod prefix

- Dockerfile.rhel7
Bug 1687247
Signed-off-by: Monis Khan <mkhan@redhat.com>
/assign @sallyom
> Bug 1687247: Update Dockerfile to match cluster-authentication-operator

- cmd/service-ca-operator/main.go
> Fix ERROR: logging before flag.Parse

- pkg/controller/configmapcainjector/controller/configmap_injecting_controller.go
- pkg/controller/configmapcainjector/controller/configmap_injecting_controller_test.go
- pkg/controller/servingcert/controller/secret_creating_controller.go
- pkg/controller/servingcert/controller/secret_updating_controller.go
- pkg/controller/servingcert/controller/secret_updating_controller_test.go
- test/e2e/e2e_test.go
This PR will ensure changes in ca bundle injector configmap and serving cert secret data are stomped on by the controller.
https://jira.coreos.com/browse/AUTH-204
> Bug 1683058: Prevent sharing of configmap and secret data

- bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
- bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
- manifests/0000_09_service-ca-operator_00_roles.yaml
- manifests/0000_09_service-ca-operator_03_cm.yaml
- manifests/0000_09_service-ca-operator_04_sa.yaml
- manifests/0000_09_service-ca-operator_05_deploy.yaml
- pkg/cmd/apiservicecabundle/cmd.go
- pkg/cmd/configmapcabundle/cmd.go
- pkg/cmd/operator/cmd.go
- pkg/cmd/servingcertsigner/cmd.go
- pkg/operator/operatorclient/interfaces.go
- pkg/operator/v4_00_assets/bindata.go
- test/e2e/e2e_test.go
Remove "openshift-" prefix from the resource names for auth components
> bug 1700903: standardize names for api freeze

- bindata/v4.0.0/apiservice-cabundle-controller/deployment.yaml
- bindata/v4.0.0/configmap-cabundle-controller/deployment.yaml
- bindata/v4.0.0/service-serving-cert-signer-controller/deployment.yaml
- hack/verify-generated-bindata.sh
- manifests/05_deploy.yaml
- pkg/operator/v4_00_assets/bindata.go
Signed-off-by: Monis Khan <mkhan@redhat.com>
> Bug 1740121: Make service-ca have guaranteed scheduling

- Dockerfile
- Dockerfile.rhel7
- Makefile
* Dockerfile(s) -add ldflags, drop `GODEBUG=tls13=1` with go build, not needed, also cleanup LABELs to match other components (KAS-O, OAS-O)
* clean up Makefile to match library-go example
> update Dockerfile, Dockerfile.rhel7 ldflags, update Makefile make images

- test/e2e/e2e_test.go
This change appears to reduce the incidence of timeout-related failure of rotation tests which have been affecting service-ca PRs lately.
> Double polling timeout that looks to be failing the rotation tests

- manifests/0000_90_service-ca-operator_01_prometheusrole.yaml
- manifests/0000_90_service-ca-operator_02_prometheusrolebinding.yaml
- manifests/0000_90_service-ca-operator_03_servicemonitor.yaml
- manifests/00_roles.yaml
- manifests/01_namespace.yaml
- manifests/02_service.yaml
- manifests/03_cm.yaml
- manifests/03_operator.cr.yaml
- manifests/04_sa.yaml
- manifests/05_deploy.yaml
- manifests/07_clusteroperator.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
> add current profile annotations to CVO manifests

- pkg/controller/cabundleinjector/starter.go
saw it in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/439/pull-ci-openshift-kubernetes-master-e2e-aws-serial/1324410771710414848, got a straight forward fix.
/cherrypick release-4.6
> bug 1895141: prevent panics in service-ca injectors

- pkg/controller/api/resourcenames.go
- pkg/operator/starter.go
> Remove cleanup of 4.3 deployments that was safe to remove in 4.5

- manifests/05_deploy.yaml
> Bug 1914446: manifests: run the operator's pod as non-root user

- pkg/controller/servingcert/controller/secret_creating_controller.go
- pkg/controller/servingcert/controller/secret_creating_controller_test.go
- pkg/operator/rotate_test.go
- test/e2e/e2e_test.go
… per discussion in https://github.com/openshift/enhancements/pull/674 .
See the individual commit messages for details.
> Generate wildcard certificates matching pod host names for headless services

- OWNERS
> Add s-urbaniak, remove marun from OWNERS

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
Helping [bot](https://github.com/openshift-bot) to get [PR](https://github.com/openshift/service-ca-operator/pull/178) merged.
> Update go version to 1.16

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
Reconciling with https://github.com/openshift/ocp-build-data/tree/f6e54c0781fee216939b0c98fb6aa82a5b3a958d/images/ose-service-ca-operator.yml
> Updating ose-service-ca-operator images to be consistent with ART

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
- go.sum
> Updating ose-cluster-authentication-operator images to be consistent with ART

- pkg/operator/sync_common.go
- pkg/operator/sync_common_test.go
The "ApplyWithForce" logic does not react to changing the Pod
template spec.
/assing @ibihim
> Bug 2048349: make the operator react to workload logLevel configuration

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
- pkg/operator/v4_00_assets/bindata.go
> [4.13] OCPBUGS-16806: Updating ose-service-ca-operator images to be consistent with ART

- README.md
Just updated broken links. It would be an easy review^
> NO-JIRA: fix outdated doc links
